#!/bin/bash
find . -name '*.jar' > /tmp/find_in_jar_tmp
while read line
do
    if unzip -1 $line | grep $1 &> /tmp/find_in_jar_tmp_second
    then
        echo $line | sed 's#\(.*\)#\x1b[1;31m\1x1b[00m#'
        cat /tmp/find_in_jar_second fi
done </tmp/find_in_jar_tmp
