#!/bin/bash
### grep text inside jars content
if [ $# -lt 2 ];then
    echo 'Usage: grep-in-clj path text'
    exit 1;
fi
LOOK_FOR=$1
LOOK_FOR=`echo ${LOOK_FOR//\./\/}`
folder=$2
echo "find '$LOOK_FOR' in $folder "
for i in `find $folder -name "*.clj"`
do
    grep "$LOOK_FOR" $i > /dev/null
    if [ $? = 0 ]
    then
        echo "==> Found \"$LOOK_FOR\" in $i"
    fi
done
